# Trading Bot Configuration

server:
  # Список разрешенных IP адресов для webhook
  allowed_ips:
    - "52.89.214.238"    # TradingView
    - "34.212.75.30"     # TradingView
    - "54.218.53.128"    # TradingView
    - "52.32.178.7"      # TradingView
    - "95.27.48.35"    # TestIP

strategies:
  # Список доступных стратегий и их статус (true = активна, false = отключена)
  # ВАЖНО: Должна быть активна только ОДНА стратегия!
  available:
    "Стратегия контрольной точки разворота (1, 1)": true
    "MACD (12, 26, 9)": false